### ISSUE TITLE
The gauge is misbehaving when the min value is not 0

### ISSUE THREAD

**Issue by vinoddavis** [ivosturm/RGraphGauge#1]
When the min value starts from 300 and max value is 850, following is how the gauge looks. Instead of starting 300, the ribbon starts from 650.

![image](https://user-images.githubusercontent.com/37645052/39381469-d8c3621e-4a27-11e8-9db4-0341ed0464f6.png)

The ring settings as follows:-
![image](https://user-images.githubusercontent.com/37645052/39381517-04a33238-4a28-11e8-82e1-84c53b514a51.png)

Please advise if this is a configuration issue or it needs an updated version.

**Comment by ivosturm** [comment]
This is indeed an issue in the widget. I have fixed it in a new release. Can you download the newest version from the Mendix AppStore (v1.1.1) and verify?
